import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Kayode Babalola",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased h-full w-full md:p-8 bg-gradient-to-b text-white from-teal-950 bg-fixed to-black/90 p-4`}
      >
        <main className="w-3/4 mx-auto h-full">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
